spring:
  application:
    name: finance
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    url_for_confirm: ${CONFIRM_URL}
    minutes_to_confirm: ${CONFIRM_MINUTES}
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

currency-rates:
  url:
    central-bank: https://cbr.ru/currency_base/daily/
    open-exchange:
      base: https://openexchangerates.org/api/
      additional: latest.json
  open-exchange:
    api-id: ${OPEN-EXCHANGE-API-ID}

auth-attempt:
  max-attempt: 5
  block-time-in-seconds: 900